'use strict';
const KEY='bedbug-log-v1', statuses=['対策中','経過観察中','再発','対応完了'], companyStatuses=['未連絡','問い合わせ済','見積済','検討中','依頼決定','施工完了'];
const rooms=['和室','寝室','リビング','子供部屋','廊下','その他'], places=['布団','ベッド','マットレス','畳','壁','床','家具','カーテン','その他'], measures=['掃除機','拭き掃除','洗濯','高温乾燥','寝具処理','殺虫剤','捕獲器設置','家具移動','物品処分','業者施工','業者へ連絡','その他'];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}, nowTime=()=>new Date().toTimeString().slice(0,5), dayValue=s=>Date.parse(s+'T00:00:00Z')/86400000;
const dateLabel=s=>s?s.replaceAll('-','/'):'未記録';
let data={version:1,status:'対策中',findings:[],actions:[],companies:[]},page='dashboard',range=7,editing=null,storageBroken=false;
function validate(d){if(!d||d.version!==1||!statuses.includes(d.status)||!['findings','actions','companies'].every(k=>Array.isArray(d[k])))throw Error('BEDBUG LOG のバックアップではありません。'); const ids=new Set();for(const k of ['findings','actions','companies'])for(const r of d[k]){if(!r||typeof r.id!=='string'||ids.has(r.id))throw Error('記録のIDが不正です。');ids.add(r.id);for(const [f,v] of Object.entries(r)){if(f==='rooms'){if(k!=='actions'||!Array.isArray(v)||!v.length||!v.every(t=>typeof t==='string'&&t.trim()&&t.length<=100))throw Error('実施した部屋を選択または入力してください。');}else if(f==='types'){if(!Array.isArray(v)||!v.length||!v.every(t=>measures.includes(t)))throw Error('対策内容が不正です。');}else if(!['string','number'].includes(typeof v))throw Error('記録の形式が不正です。');}if(k!=='companies'){if(!validDate(r.date)||r.date>today()||!/^([01]\d|2[0-3]):[0-5]\d$/.test(r.time)||!r.room)throw Error('記録の日時・部屋が不正です。');}if(k==='findings'&&(!Number.isSafeInteger(r.count)||r.count<1||!['生きていた','死んでいた','不明'].includes(r.state)||!r.place))throw Error('発見記録が不正です。');if(k==='actions'&&(!Array.isArray(r.types)||!r.types.length))throw Error('対策記録が不正です。');if(k==='companies'&&(!r.name||!companyStatuses.includes(r.status)||(r.price!==''&&(!Number.isFinite(Number(r.price))||Number(r.price)<0))))throw Error('業者情報が不正です。');for(const f of ['contact','scheduled'])if(r[f]&&!validDate(r[f]))throw Error('日付が不正です。');}return d;}
function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(dayValue(s))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;}
try{const saved=localStorage.getItem(KEY);if(saved)data=validate(JSON.parse(saved));}catch(e){storageBroken=true;}
function persist(next){if(storageBroken){toast('保存済みデータを読み込めません。データ管理からバックアップを復元してください。');return false;}try{localStorage.setItem(KEY,JSON.stringify(next));data=next;return true;}catch(e){toast('保存できませんでした。ブラウザの保存設定・空き容量をご確認ください。');return false;}}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',5000);}
function summary(){const t=today(),all=data.findings,latest=[...all].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))[0];return {total:all.reduce((n,r)=>n+r.count,0),today:all.filter(r=>r.date===t).reduce((n,r)=>n+r.count,0),week:all.filter(r=>dayValue(t)-dayValue(r.date)>=0&&dayValue(t)-dayValue(r.date)<7).reduce((n,r)=>n+r.count,0),last:latest?.date||'',days:latest?Math.floor(dayValue(t)-dayValue(latest.date)):null};}
function statusControl(){return `<div class="status"><label for="status">現在のステータス</label><select id="status">${options(statuses,data.status)}</select></div>`;}
function options(items,v){return items.map(s=>`<option${s===v?' selected':''}>${esc(s)}</option>`).join('');}
function hero(observe=false){const s=summary();return `<section class="hero"><div class="eyebrow">${observe?'OBSERVATION':'OVERVIEW'}</div><div class="hero-top"><div><p class="days-label">${observe?'最後にトコジラミを確認してから':'最終発見から'}</p><div class="days">${s.days===null?'—':s.days}<small>日</small></div><p class="subtle">最終発見日：${dateLabel(s.last)}</p></div>${statusControl()}</div>${observe?'<p class="notice">記録上の経過日数です。駆除完了を示すものではありません。状況に合わせてステータスを変更してください。</p>':`<div class="stats"><div class="stat"><span>今日の発見数</span><strong>${s.today}<small>匹</small></strong></div><div class="stat"><span>累計発見数</span><strong>${s.total}<small>匹</small></strong></div><div class="stat"><span>直近7日間</span><strong>${s.week}<small>匹</small></strong></div><div class="stat"><span>対策実施回数</span><strong>${data.actions.length}<small>回</small></strong></div></div>`}<div class="actions"><button class="primary" data-add="findings">＋ 発見を記録</button><button data-add="actions">＋ 対策を記録</button></div></section>`;}
function chart(){const dates=Array.from({length:range},(_,i)=>{const d=new Date(today()+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-range+1+i);return d.toISOString().slice(0,10)}),counts=dates.map(date=>data.findings.filter(r=>r.date===date).reduce((n,r)=>n+r.count,0)),max=Math.max(1,...counts);return `<section class="section panel"><div class="section-head"><h2>発見数の推移</h2><div class="segments" aria-label="表示期間">${[7,14,30].map(n=>`<button data-range="${n}" class="${range===n?'selected':''}" aria-pressed="${range===n}">${n}日間</button>`).join('')}</div></div><p class="subtle">日別の発見数 <span>／ 匹</span></p><div class="chart" role="img" aria-label="${dates.map((d,i)=>`${d}: ${counts[i]}匹`).join('、')}">${counts.map((n,i)=>`<div class="bar-wrap" title="${dateLabel(dates[i])}：${n}匹"><span class="bar-number">${n||''}</span><div class="bar" style="height:${n/max*140}px"></div></div>`).join('')}</div><div class="chart-labels"><span>${dateLabel(dates[0]).slice(5)}</span><span>${dateLabel(dates[Math.floor(range/2)]).slice(5)}</span><span>${dateLabel(dates[range-1]).slice(5)}</span></div><p class="chart-note">記録のない日は0匹と表示しています。</p></section>`;}
function roomView(){const sums=Object.create(null);data.findings.forEach(r=>sums[r.room]=(sums[r.room]||0)+r.count);const pairs=Object.entries(sums).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...Object.values(sums));return `<section class="section panel"><div class="section-head"><h2>部屋別の発見数</h2><span class="subtle">累計</span></div>${pairs.length?pairs.map(([r,n])=>`<div class="room"><div class="room-row"><span>${esc(r)}</span><span><strong>${n}</strong> 匹</span></div><div class="track"><div style="width:${n/max*100}%"></div></div></div>`).join(''):empty('部屋ごとの記録はまだありません','発見を記録すると、ここに集計されます。')}</section>`;}
function empty(a,b=''){return `<div class="empty"><strong>${a}</strong>${b}</div>`;}
function timeline(limit){const events=[...data.findings.map(r=>({...r,kind:'findings'})),...data.actions.map(r=>({...r,kind:'actions'}))].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));return (limit?events.slice(0,limit):events).map(r=>`<article class="event"><span class="dot ${r.kind==='findings'?'finding':''}"></span><div class="event-body"><time>${dateLabel(r.date)} ${esc(r.time)}</time><h3>${esc(r.kind==='actions'?actionRooms(r).join('・'):r.room)}${r.kind==='findings'?`で${r.count}匹発見`:' · '+r.types.map(esc).join('・')}</h3><p>${r.kind==='findings'?`${esc(r.place)} ／ ${esc(r.state)}`:[r.product&&'商品：'+r.product,r.usePlace&&'使用場所：'+r.usePlace].filter(Boolean).map(esc).join(' ／ ')}</p>${r.memo?`<p>${esc(r.memo)}</p>`:''}</div><div class="edit-actions"><button data-edit="${r.kind}" data-id="${esc(r.id)}">編集</button><button data-delete="${r.kind}" data-id="${esc(r.id)}" aria-label="${dateLabel(r.date)}の記録を削除">削除</button></div></article>`).join('')||empty('まだ記録がありません','発見したこと・実施したことを、ここから残していきましょう。');}
function companies(){return `<div class="section-head"><div><h1>業者比較</h1><p class="view-intro">見積・施工内容・連絡先をまとめて比較。</p></div><button class="primary" data-add="companies">＋ 業者を追加</button></div><div class="company-grid">${data.companies.map(r=>`<article class="panel company"><div class="section-head"><h2>${esc(r.name)}</h2><span class="badge">${esc(r.status)}</span></div><p class="price">${r.price===''?'見積未登録':'¥'+Number(r.price).toLocaleString('ja-JP')}</p><dl>${[['contact','連絡日'],['scheduled','施工予定日'],['detail','施工内容'],['warranty','保証期間'],['conditions','再施工条件'],['person','担当者'],['phone','電話番号'],['memo','メモ']].map(([k,l])=>`<dt>${l}</dt><dd>${esc(r[k]||'—')}</dd>`).join('')}</dl><div class="edit-actions"><button data-edit="companies" data-id="${esc(r.id)}">編集</button><button data-delete="companies" data-id="${esc(r.id)}">削除</button></div></article>`).join('')}</div>${data.companies.length?'':empty('比較する業者はまだありません','会社名だけでも登録できます。')}`;}
function render(){document.querySelectorAll('[data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false');});$('#main').innerHTML=(storageBroken?'<p class="notice" role="alert">保存済みデータを読み込めませんでした。元のデータを保護するため保存を停止しています。データ管理から元データの書き出し・復元ができます。</p>':'')+(page==='dashboard'?hero()+`<div class="columns">${chart()}${roomView()}</div><section class="section panel"><div class="section-head"><h2>最近の記録</h2><button data-go="timeline">すべて見る →</button></div>${timeline(5)}</section>`:page==='timeline'?`<div class="section-head"><div><h1>タイムライン</h1><p class="view-intro">発見と対策を、新しい順に。</p></div></div><div class="actions"><button class="primary" data-add="findings">＋ 発見を記録</button><button data-add="actions">＋ 対策を記録</button></div><section class="section panel">${timeline()}</section>`:page==='companies'?companies():page==='observation'?hero(true)+chart():`<h1>データ管理</h1><p class="view-intro">大切な記録を、バックアップして保管。</p><section class="section panel"><h2>バックアップと復元</h2><p class="view-intro">データはこのブラウザに保存されます。履歴やサイトデータを消去すると記録も消えるため、定期的にJSONファイルを保存してください。別端末への自動同期はありません。</p><div class="data-actions"><button class="primary" id="export">JSONでバックアップ</button><button id="import">JSONから復元</button><input type="file" id="import-file" accept=".json,application/json" hidden></div><p class="notice">復元は現在の記録に追加・統合します。同じIDの記録はバックアップの内容で更新し、ステータスも復元します。</p><p class="subtle" style="margin-top:15px">発見 ${data.findings.length}件 ／ 対策 ${data.actions.length}件 ／ 業者 ${data.companies.length}社</p></section>`);}
function field(name,label,type='text',value='',extra=''){return `<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(name,label,items,value){return `<label class="field"><span>${label}</span><select name="${name}">${options(items,value)}</select></label>`;}
function memo(value){return `<label class="field"><span>メモ</span><textarea name="memo" maxlength="10000">${esc(value)}</textarea></label>`;}
function actionRooms(r){return r.rooms || (r.room?[r.room]:[]);}
function actionRoomFields(r){const selected=actionRooms(r),custom=selected.filter(s=>!rooms.includes(s));return `<fieldset><legend>実施した部屋 *（複数選択可）</legend><div class="checks">${rooms.map(s=>`<label class="check"><input type="checkbox" name="rooms" value="${esc(s)}" ${selected.includes(s)?'checked':''}>${esc(s)}</label>`).join('')}</div></fieldset>${field('customRooms','ほかの部屋（自由入力）','text',custom.join('、'),'maxlength="1000" placeholder="例：玄関、洗面所"')}<p class="subtle">複数入力するときは「、」で区切ってください。</p>`;}
function openEditor(kind,id){const r=id?data[kind].find(r=>r.id===id):{};editing={kind,id};$('#form-title').textContent=(kind==='findings'?'発見':kind==='actions'?'対策':'業者')+(id?'を編集':'を記録');$('#form-error').textContent='';let html='';if(kind!=='companies'){html=`<div class="pair">${field('date','日付 *','date',r.date||today(),`required max="${today()}"`)}${field('time','時刻 *','time',r.time||nowTime(),'required')}</div>${kind==='actions'?actionRoomFields(r):field('room','部屋 *','text',r.room||'','required list="rooms" maxlength="100" placeholder="候補から選択、または自由入力"')+`<datalist id="rooms">${rooms.map(s=>`<option value="${s}">`).join('')}</datalist>`}`;if(kind==='findings')html+=field('place','発見場所 *','text',r.place||'','required list="places" maxlength="100" placeholder="布団、壁など"')+`<datalist id="places">${places.map(s=>`<option value="${s}">`).join('')}</datalist><div class="pair">${field('count','匹数 *','number',r.count||1,'min="1" max="1000000" step="1" required')}${select('state','状態',['生きていた','死んでいた','不明'],r.state||'生きていた')}</div>`;else html+=`<fieldset><legend>対策内容 *（複数選択可）</legend><div class="checks">${measures.map(s=>`<label class="check"><input type="checkbox" name="types" value="${s}" ${(r.types||[]).includes(s)?'checked':''}>${s}</label>`).join('')}</div></fieldset>${field('product','使用した商品・薬剤','text',r.product||'','maxlength="200"')}${field('usePlace','商品・薬剤の使用場所','text',r.usePlace||'','maxlength="200" placeholder="例：ベッドフレームの隙間"')}<p class="subtle">使用日時は上の「日付・時刻」で記録します。薬剤は製品表示・メーカー説明に従ってください。</p>`;}else html=field('name','会社名 *','text',r.name||'','required maxlength="200"')+select('status','ステータス',companyStatuses,r.status||'未連絡')+`<div class="pair">${field('contact','連絡日','date',r.contact||'')}${field('price','見積金額（円）','number',r.price??'','min="0" max="1000000000" step="1"')}</div>`+field('detail','施工内容','text',r.detail||'','maxlength="2000"')+field('scheduled','施工予定日','date',r.scheduled||'')+field('warranty','保証期間','text',r.warranty||'','maxlength="200"')+field('conditions','再施工条件','text',r.conditions||'','maxlength="2000"')+`<div class="pair">${field('person','担当者','text',r.person||'','maxlength="200"')}${field('phone','電話番号','tel',r.phone||'','maxlength="100"')}</div>`;$('#fields').innerHTML=html+memo(r.memo||'');$('#editor').showModal();}
$('#form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),r=Object.fromEntries(f.entries());for(const k in r)r[k]=r[k].trim();r.id=editing.id||crypto.randomUUID();if(editing.kind==='findings')r.count=Number(r.count);if(editing.kind==='actions'){r.types=f.getAll('types');r.rooms=[...new Set([...f.getAll('rooms'),...(r.customRooms||'').split(/[、,，]/)].map(s=>s.trim()).filter(Boolean))];r.room=r.rooms.join('・');delete r.customRooms;}const next=structuredClone(data);if(editing.id)next[editing.kind]=next[editing.kind].map(x=>x.id===editing.id?r:x);else next[editing.kind].push(r);try{validate(next);}catch(err){$('#form-error').textContent=err.message;return;}if(persist(next)){$('#editor').close();render();toast('記録を保存しました');}});
$('#close').onclick=$('#cancel').onclick=()=>$('#editor').close();
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.page||d.go){page=d.page||d.go;render();}if(d.add)openEditor(d.add);if(d.edit)openEditor(d.edit,d.id);if(d.delete&&confirm('この記録を削除しますか？この操作は取り消せません。')){const next=structuredClone(data);next[d.delete]=next[d.delete].filter(r=>r.id!==d.id);if(persist(next)){render();toast('記録を削除しました');}}if(d.range){range=Number(d.range);render();}if(b.id==='export'){let raw;try{raw=storageBroken?localStorage.getItem(KEY):JSON.stringify(data,null,2);}catch(err){toast('データにアクセスできません。');return;}const url=URL.createObjectURL(new Blob([raw||''],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`bedbug-log-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(b.id==='import')$('#import-file').click();});
document.addEventListener('change',async e=>{if(e.target.id==='status'){const old=data.status;if(persist({...data,status:e.target.value}))toast('ステータスを変更しました');else e.target.value=old;}if(e.target.id==='import-file'){const file=e.target.files[0];if(!file)return;try{if(file.size>4000000)throw Error('ファイルは4MB以下にしてください。');const restored=validate(JSON.parse(await file.text()));const next=structuredClone(data);for(const k of ['findings','actions','companies']){const m=new Map(next[k].map(r=>[r.id,r]));restored[k].forEach(r=>m.set(r.id,r));next[k]=[...m.values()];}next.status=restored.status;validate(next);const wasBroken=storageBroken;storageBroken=false;if(persist(next)){render();toast('バックアップを復元しました');}else storageBroken=wasBroken;}catch(err){toast('復元できません：'+err.message);}e.target.value='';}});
window.addEventListener('storage',e=>{if(e.key===KEY){try{if(e.newValue){data=validate(JSON.parse(e.newValue));storageBroken=false;render();}}catch(err){toast('別タブの更新を読み込めませんでした。');}}});
render();
setInterval(()=>{if(!$('#editor').open&&page!=='data'&&page!=='companies')render();},60000);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_bedbug_summary',description:'現在の記録に基づく発見数・経過日数・対応ステータスを取得する',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...summary(),status:data.status,actionCount:data.actions.length})})).catch(()=>{});}catch{}}
